/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import domain.Client;
import domain.Course;
import domain.Purchase;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logic.Controller;

/**
 *
 * @author Ivan
 */
public class FCreatePurchase extends javax.swing.JDialog {

    /**
     * Creates new form FCreatePurchase
     */
    public FCreatePurchase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateComboClients();
        populateComboCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboClients = new javax.swing.JComboBox<>();
        jbtnSelectClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboCourses = new javax.swing.JComboBox<>();
        jbtnSelectCourse = new javax.swing.JButton();
        jbtnCreatePurchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create purhcase");

        jLabel1.setText("Select client:");

        jbtnSelectClient.setText("Select");

        jLabel2.setText("Select course:");

        jbtnSelectCourse.setText("Select");

        jbtnCreatePurchase.setText("Create purchase");
        jbtnCreatePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreatePurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboCourses, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE)
                                    .addComponent(jComboClients, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnSelectClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnSelectCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jbtnCreatePurchase)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSelectClient))
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSelectCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jbtnCreatePurchase)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreatePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreatePurchaseActionPerformed
        Client selectedClient = (Client) jComboClients.getSelectedItem();
        Course selectedCourse = (Course) jComboCourses.getSelectedItem();

        if (selectedClient != null && selectedCourse != null) {
            Purchase createdPurhcase = new Purchase(selectedCourse, selectedClient, new Date());
            Purchase insertedPurhcase = Controller.getInstance().insertPurhcase(createdPurhcase);
            if (insertedPurhcase != null) {
                JOptionPane.showMessageDialog(this, "Successful creation of purchase!");
                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Issue in creation of purchase!");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a client and a course!");
            return;
        }
    }//GEN-LAST:event_jbtnCreatePurchaseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Client> jComboClients;
    private javax.swing.JComboBox<Course> jComboCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCreatePurchase;
    private javax.swing.JButton jbtnSelectClient;
    private javax.swing.JButton jbtnSelectCourse;
    // End of variables declaration//GEN-END:variables

    private void populateComboClients() {
        List<Client> allClients = Controller.getInstance().getAllClients();
        for (Client client : allClients) {
            jComboClients.addItem(client);
        }
        jComboClients.setSelectedItem(null);
    }

    private void populateComboCourses() {
        List<Course> allCourses = Controller.getInstance().getAllCourses();
        for (Course course : allCourses) {
            jComboCourses.addItem(course);
        }
        jComboCourses.setSelectedItem(null);
    }
}
