/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import domain.Admin;
import forms.FNewCourse;
import enums.FormMode;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import forms.FSearchProfessor;
import forms.FProfessor;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author Ivan
 */
public class FMain extends javax.swing.JFrame {

    public static Socket socket;

    /**
     * Creates new form jFrameMain
     */
    public FMain() {
        initComponents();
        setVisible(true);
        setExtendedState(FMain.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jlblUserWelcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuItemEditProf = new javax.swing.JMenuItem();
        jMenuCourse = new javax.swing.JMenu();
        jMenuItemNewCourse = new javax.swing.JMenuItem();
        jMenuItemSearchCourses = new javax.swing.JMenuItem();
        jMenuConnection = new javax.swing.JMenu();
        jMenuItemConnectionServer = new javax.swing.JMenuItem();
        jMenuClient = new javax.swing.JMenu();
        jMenuItemClient = new javax.swing.JMenuItem();
        jMenuPurchase = new javax.swing.JMenu();
        jMenuItemCreatePurchase = new javax.swing.JMenuItem();
        jMenuItemSearchPurchase = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ivan's app");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jlblUserWelcome.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jlblUserWelcome.setText("Welcome ");

        jMenu1.setText("Professor");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmenuItemEditProf.setText("Edit");
        jmenuItemEditProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItemEditProfActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuItemEditProf);

        jMenuBar1.add(jMenu1);

        jMenuCourse.setText("Course");

        jMenuItemNewCourse.setText("New");
        jMenuItemNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewCourseActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuItemNewCourse);

        jMenuItemSearchCourses.setText("Search");
        jMenuItemSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchCoursesActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuItemSearchCourses);

        jMenuBar1.add(jMenuCourse);

        jMenuConnection.setText("Connection");

        jMenuItemConnectionServer.setText("Server");
        jMenuItemConnectionServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectionServerActionPerformed(evt);
            }
        });
        jMenuConnection.add(jMenuItemConnectionServer);

        jMenuBar1.add(jMenuConnection);

        jMenuClient.setText("Client");

        jMenuItemClient.setText("Edit");
        jMenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientActionPerformed(evt);
            }
        });
        jMenuClient.add(jMenuItemClient);

        jMenuBar1.add(jMenuClient);

        jMenuPurchase.setText("Purchase");

        jMenuItemCreatePurchase.setText("Create");
        jMenuItemCreatePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreatePurchaseActionPerformed(evt);
            }
        });
        jMenuPurchase.add(jMenuItemCreatePurchase);

        jMenuItemSearchPurchase.setText("Search");
        jMenuItemSearchPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchPurchaseActionPerformed(evt);
            }
        });
        jMenuPurchase.add(jMenuItemSearchPurchase);

        jMenuBar1.add(jMenuPurchase);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jlblUserWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlblUserWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewCourseActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog jDialNewCourse = new FNewCourse(this, true);
        jDialNewCourse.setVisible(true);
    }//GEN-LAST:event_jMenuItemNewCourseActionPerformed

    private void jmenuItemEditProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItemEditProfActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog professorDialog = new FProfessor(this, true);
        professorDialog.setVisible(true);
    }//GEN-LAST:event_jmenuItemEditProfActionPerformed

    private void jMenuItemConnectionServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectionServerActionPerformed
        JDialog jDialogServerConnectionDetails = new FConnect(this, true);
        jDialogServerConnectionDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItemConnectionServerActionPerformed

    private void jMenuItemSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchCoursesActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog searchCourses = new FSearchCourse(this, true, FormMode.VIEW);
        searchCourses.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchCoursesActionPerformed

    private void jMenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog clientDialog = new FClient(this, true);
        clientDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Admin loggedAdmin = Session.getInstance().getAdmin();
        jlblUserWelcome.setText("Welcome " + loggedAdmin.getFirstName() + " " + loggedAdmin.getLastName());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemCreatePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreatePurchaseActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog createPurhcase = new FCreatePurchase(this, true);
        createPurhcase.setVisible(true);
    }//GEN-LAST:event_jMenuItemCreatePurchaseActionPerformed

    private void jMenuItemSearchPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchPurchaseActionPerformed
        if (Session.getInstance().getSocket() == null) {
            JOptionPane.showMessageDialog(null, "Please connect to server!");
            return;
        }
        JDialog searchPurchases = new FSearchPurchases(this, true);
        searchPurchases.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchPurchaseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClient;
    private javax.swing.JMenu jMenuConnection;
    private javax.swing.JMenu jMenuCourse;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemClient;
    private javax.swing.JMenuItem jMenuItemConnectionServer;
    private javax.swing.JMenuItem jMenuItemCreatePurchase;
    private javax.swing.JMenuItem jMenuItemNewCourse;
    private javax.swing.JMenuItem jMenuItemSearchCourses;
    private javax.swing.JMenuItem jMenuItemSearchPurchase;
    private javax.swing.JMenu jMenuPurchase;
    private javax.swing.JLabel jlblUserWelcome;
    private javax.swing.JMenuItem jmenuItemEditProf;
    // End of variables declaration//GEN-END:variables
}
