/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import domain.Course;
import domain.Lesson;
import domain.LessonType;
import domain.Professor;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import logic.Controller;
import forms.FSearchProfessor;
import session.Session;
import tableModels.CourseWithLessonsTableModel;

/**
 *
 * @author Ivan
 */
public class FNewCourse extends javax.swing.JDialog {

    /**
     * Creates new form jDialogNewCourse
     */
    public FNewCourse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateComboBoxProfessor();
        setLessonTableMyModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jtxtTitle = new javax.swing.JTextField();
        jtxtPrice = new javax.swing.JTextField();
        jlblPrice = new javax.swing.JLabel();
        jlblDuration = new javax.swing.JLabel();
        jtxtDuration = new javax.swing.JTextField();
        jlblProfessor = new javax.swing.JLabel();
        jComboBoxSelectProfessor = new javax.swing.JComboBox<>();
        jbtnSelectProfessor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLessons = new javax.swing.JTable();
        jtbnAddLesson = new javax.swing.JButton();
        jtbnRemoveLesson = new javax.swing.JButton();
        jbtnSaveCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Course");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jlblTitle.setText("Title");

        jtxtTitle.setText(" ");

        jlblPrice.setText("Price");

        jlblDuration.setText("Duration (min)");

        jtxtDuration.setEditable(false);
        jtxtDuration.setText(" ");

        jlblProfessor.setText("Professor");

        jComboBoxSelectProfessor.setEditable(true);
        jComboBoxSelectProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectProfessorActionPerformed(evt);
            }
        });

        jbtnSelectProfessor.setText("Select");
        jbtnSelectProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelectProfessorActionPerformed(evt);
            }
        });

        jtblLessons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lesson Number", "Name", "Duration", "Tablature", "Type"
            }
        ));
        jScrollPane1.setViewportView(jtblLessons);

        jtbnAddLesson.setText("+");
        jtbnAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnAddLessonActionPerformed(evt);
            }
        });

        jtbnRemoveLesson.setText("-");
        jtbnRemoveLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnRemoveLessonActionPerformed(evt);
            }
        });

        jbtnSaveCourse.setText("Save course");
        jbtnSaveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtbnRemoveLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtbnAddLesson, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPrice)
                                    .addComponent(jlblTitle)
                                    .addComponent(jlblProfessor)
                                    .addComponent(jlblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxSelectProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jbtnSelectProfessor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jbtnSaveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTitle)
                    .addComponent(jtxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblPrice)
                    .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDuration)
                    .addComponent(jtxtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblProfessor)
                    .addComponent(jComboBoxSelectProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSelectProfessor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jtbnAddLesson)
                        .addGap(30, 30, 30)
                        .addComponent(jtbnRemoveLesson)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSaveCourse)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSelectProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelectProfessorActionPerformed
        JDialog jdSearchProf = new FSearchProfessor(null, true);
        jdSearchProf.setVisible(true);
    }//GEN-LAST:event_jbtnSelectProfessorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (Session.getInstance().getMap().containsKey("selected_prof")) {
            Professor prof = (Professor) Session.getInstance().getMap().get("selected_prof");
            jComboBoxSelectProfessor.setSelectedItem(prof);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jtbnAddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnAddLessonActionPerformed
        CourseWithLessonsTableModel ctm = (CourseWithLessonsTableModel) jtblLessons.getModel();
        ctm.addNewRow();
        jtxtDuration.setText(ctm.getCurrentDuration() + "");
    }//GEN-LAST:event_jtbnAddLessonActionPerformed

    private void jtbnRemoveLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnRemoveLessonActionPerformed
        int selectedLesson = jtblLessons.getSelectedRow();
        if (selectedLesson > -1) {
            CourseWithLessonsTableModel ctm = (CourseWithLessonsTableModel) jtblLessons.getModel();
            ctm.removeSelectedRow(selectedLesson);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a lesson in order to delete!");
        }


    }//GEN-LAST:event_jtbnRemoveLessonActionPerformed

    private void jbtnSaveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveCourseActionPerformed
        if (jtxtTitle.getText() == null || jtxtTitle.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a course title!");
            return;
        }
        if (jtxtPrice.getText() == null || jtxtPrice.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a price!");
            return;
        }
        CourseWithLessonsTableModel ctm = (CourseWithLessonsTableModel) jtblLessons.getModel();
        if (ctm.getCourseLessons().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course must have at least one lesson!");
        }

        try {
            double coursePriceTest = Double.parseDouble(jtxtPrice.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Insert a valid price!");
        }

        double coursePrice = Double.parseDouble(jtxtPrice.getText().trim());
        Course courseToSave = ctm.getCourse();
        courseToSave.setProfessor((Professor) jComboBoxSelectProfessor.getSelectedItem());
        courseToSave.setName(jtxtTitle.getText().trim());
        courseToSave.setDuration(Integer.parseInt(jtxtDuration.getText().trim()));
        courseToSave.setPrice(coursePrice);

        Course savedCourse = Controller.getInstance().saveCourse(courseToSave);
        if (savedCourse != null) {
            JOptionPane.showMessageDialog(this, "Successful insertion of course!");
        } else {
            JOptionPane.showMessageDialog(this, "Issue inserting course!");
        }


    }//GEN-LAST:event_jbtnSaveCourseActionPerformed

    private void jComboBoxSelectProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectProfessorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> jComboBoxSelectProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSaveCourse;
    private javax.swing.JButton jbtnSelectProfessor;
    private javax.swing.JLabel jlblDuration;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblProfessor;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTable jtblLessons;
    private javax.swing.JButton jtbnAddLesson;
    private javax.swing.JButton jtbnRemoveLesson;
    private javax.swing.JTextField jtxtDuration;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtTitle;
    // End of variables declaration//GEN-END:variables

    public void populateComboBoxProfessor() {
        List<Professor> professors = Controller.getInstance().getAllProfessors();
        for (Professor professor : professors) {
            jComboBoxSelectProfessor.addItem(professor);
        }
        jComboBoxSelectProfessor.setSelectedItem(null);
    }

    private void setLessonTableMyModel() {
        Course course = new Course();

        CourseWithLessonsTableModel ctm = new CourseWithLessonsTableModel(course);
        jtblLessons.setModel(ctm);

        LessonType[] lessonTypes = LessonType.values();
        JComboBox comboLessonType = new JComboBox(new DefaultComboBoxModel(lessonTypes));

        TableColumnModel colModel = jtblLessons.getColumnModel();
        TableColumn colLessonType = colModel.getColumn(4);
        colLessonType.setCellEditor(new DefaultCellEditor(comboLessonType));
    }

}
