/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import domain.Course;
import enums.FormMode;
import java.util.List;
import javafx.beans.binding.Bindings;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logic.Controller;
import session.Session;
import tableModels.AllCoursesTableModel;

/**
 *
 * @author Ivan
 */
public class FSearchCourse extends javax.swing.JDialog {

    /**
     * Creates new form FSearchCourse
     */
    public FSearchCourse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateTableAllCourses();
        prepareForSort();
    }

    public FSearchCourse(java.awt.Frame parent, boolean modal, FormMode mode) {
        super(parent, modal);
        initComponents();
        populateTableAllCourses();
        prepareForSort();

        switch (mode) {
            case SELECT:
                jbtnDetails.setEnabled(true);
                jbtnSelect.setEnabled(true);
                break;
            case VIEW:
                jbtnDetails.setEnabled(true);
                jbtnSelect.setEnabled(false);
                break;
            default:
                jbtnDetails.setEnabled(true);
                jbtnSelect.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCourses = new javax.swing.JTable();
        jbtnDetails = new javax.swing.JButton();
        jbtnSelect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtNameSearchCourse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search courses");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCourses);

        jbtnDetails.setText("Details");
        jbtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetailsActionPerformed(evt);
            }
        });

        jbtnSelect.setText("Select");

        jLabel1.setText("Search courses:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jbtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jbtnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNameSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNameSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDetails, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSelect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetailsActionPerformed
        int selectedIndex = jtblCourses.getSelectedRow();
        if (selectedIndex > -1) {
            AllCoursesTableModel tableModel = (AllCoursesTableModel) jtblCourses.getModel();
            Course selectedCourse = tableModel.getCourses().get(selectedIndex);

            Session.getInstance().getMap().put("selected_course", selectedCourse);
            JDialog courseDetails = new FUpdateDeleteCourse(null, true);
            courseDetails.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a course to see details!");
            return;
        }
    }//GEN-LAST:event_jbtnDetailsActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        Course deletedCourse = (Course) Session.getInstance().getMap().get("deleted_course");
//        Course updatedCourse = (Course) Session.getInstance().getMap().get("updated_course");
//        if(deletedCourse != null){
//            AllCoursesTableModel tableModel = (AllCoursesTableModel) jtblCourses.getModel();
//            tableModel.getCourses().remove(deletedCourse);
//            tableModel.fireTableDataChanged();
//            Session.getInstance().getMap().remove("selected_course");
//        }
//        if(updatedCourse != null){
//            AllCoursesTableModel tableModel = (AllCoursesTableModel) jtblCourses.getModel();
//            tableModel.getCourses().remove((Course)Session.getInstance().getMap().get("selected_course"));
//            tableModel.getCourses().add(updatedCourse);
//            tableModel.fireTableDataChanged();
//            Session.getInstance().getMap().remove("selected_course");
//        }
        populateTableAllCourses();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetails;
    private javax.swing.JButton jbtnSelect;
    private javax.swing.JTable jtblCourses;
    private javax.swing.JTextField jtxtNameSearchCourse;
    // End of variables declaration//GEN-END:variables

    private void populateTableAllCourses() {
        List<Course> allCourses = Controller.getInstance().getAllCourses();
        AllCoursesTableModel tableModel = new AllCoursesTableModel(allCourses);
        jtblCourses.setModel(tableModel);
    }

    private void prepareForSort() {
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(jtblCourses.getModel());
        jtblCourses.setRowSorter(rowSorter);

        jtxtNameSearchCourse.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                String filterPurchase = jtxtNameSearchCourse.getText();
                if (filterPurchase.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filterPurchase));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                String text = jtxtNameSearchCourse.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
}
