/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serverForm;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import util.UserTableModel;
import thread.ThreadRefreshUsers;
import thread.ThreadServer;
import util.Session;
import util.User;

/**
 *
 * @author Ivan
 */
public class FServer extends javax.swing.JFrame {

    private ThreadServer server;
    private ThreadRefreshUsers refreshUsers;
    private UserTableModel utm;

    /**
     * Creates new form jFrameMain
     */
    public FServer() {
        initComponents();
        setVisible(true);
        setUserTableModel();
//        setExtendedState(FServer.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jbtnStopServer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUsers = new javax.swing.JTable();
        jbtnRemoveClient = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDBConnection = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        jButton1.setText("Start Server");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnStopServer.setText("Stop Server");
        jbtnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStopServerActionPerformed(evt);
            }
        });

        jtblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblUsers);

        jbtnRemoveClient.setText("Remove Client");
        jbtnRemoveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveClientActionPerformed(evt);
            }
        });

        jMenu1.setText("Properties");

        jMenuItemDBConnection.setText("DB Connection");
        jMenuItemDBConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDBConnectionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDBConnection);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnRemoveClient, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnStopServer)
                    .addComponent(jButton1)
                    .addComponent(jbtnRemoveClient))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (server == null || !server.isAlive()) {
            server = new ThreadServer(9009);
            server.start();
            refreshUsers = new ThreadRefreshUsers(utm);
            refreshUsers.start();
            JOptionPane.showMessageDialog(null, "Server started!");
        } else {
            JOptionPane.showMessageDialog(null, "Server already started?");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemDBConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDBConnectionActionPerformed
        JDialog dbConnectionForm = new FDBConnect(this, true);
        dbConnectionForm.setVisible(true);
    }//GEN-LAST:event_jMenuItemDBConnectionActionPerformed

    private void jbtnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStopServerActionPerformed
        if (server != null && server.isAlive()) {
            utm.removeClients();
            System.out.println("Clients removed from model");
            try {
                server.removeClients();
                System.out.println("Client threads stopped and server interrupted");
                server.getServerSocket().close();
                server = null;
                System.out.println(server);
            } catch (IOException ex) {
                Logger.getLogger(FServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnStopServerActionPerformed

    private void jbtnRemoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveClientActionPerformed
        int selectedRow = jtblUsers.getSelectedRow();
        if (selectedRow >= 0) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this client?", "Confirm",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                User clientToRemove = utm.getUsers().get(selectedRow);
                Session.getInstance().getUsers().remove(clientToRemove);
                utm.removeClient(selectedRow);
                server.removeClient(clientToRemove);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a client!");
        }
    }//GEN-LAST:event_jbtnRemoveClientActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemDBConnection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnRemoveClient;
    private javax.swing.JButton jbtnStopServer;
    private javax.swing.JTable jtblUsers;
    // End of variables declaration//GEN-END:variables

    private void setUserTableModel() {
        List<User> users = new ArrayList<User>();
        utm = new UserTableModel(users);
        jtblUsers.setModel(utm);
    }
}
